version: '3.8'

services:
  app:
    build: .
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    # restart: always
    volumes:
      - .env:/root/.env

    networks:
      - application

  mongo:
    # restart: always
    image: mongo:latest
    volumes:
      - ./data:/data/d
    ports:
      - 27017:27017
    env_file:
      - .env
    networks:
      - application

networks:
  application:
    driver: bridge
