version: '3.8'

services:
  app:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    # restart: always
    volumes:
      - ./.env:/root/.env

    networks:
      - application

  mongo:
    # restart: always
    image: mongo:latest
    volumes:
      - ./.data:/data/db
    ports:
      - 27017:27017
    env_file:
      - .env
    networks:
      - application
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

networks:
  application:
    driver: bridge
